### ISSUE TITLE
Bash project

### ISSUE THREAD

**Issue by allseenn** [allseenn/zoo#1]
Create bash dir and scripts that creates animals due the task.pdf

**Comment by strogino** [comment]
Ok, i will make it as soon as possible!

**Comment by strogino** [comment]
Я сделаю директорияю bash и туда буду добавлять скрипты по заданию

**Comment by strogino** [comment]
Создал скрипт mysql.sh, который сетапит родную мусклу в убунту и запускает ее демоном

**Comment by allseenn** [comment]
проверил mysql.sh - пока пойдет

**Comment by allseenn** [comment]
проверил mysql.sh - пока пойдет
